# Generated by Django 5.1.2 on 2024-10-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
